// JIH

#pragma once

#include "NativeGameplayTags.h"

namespace MWGameplayTags
{
	/* Input Tags */
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialAbility_ForcePush);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialAbility_Slam);

	/* Player Tags */
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Recovery);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SpecialAbility_ForcePush);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SpecialAbility_DoubleJump);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SpecialAbility_Slam);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SaveAttack);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ResetAttack);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_ComboCount);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_IsAttacking);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_IsFalling);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_IsGrounded);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_OnDoubleJumping);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialAbility_ForcePush);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialAbility_DoubleJump);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialAbility_Slam);

	/* Shared Tags */
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Knockback);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Knockback);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Death);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_AOE);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_SpecialAbilityDamage);

	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	MW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);

}

